<?php

namespace Cvut\Fit\BiWt1\Blog\CommonBundle\Entity;

use Cvut\Fit\BiWt1\Blog\CommonBundle\Doctrine\Repository\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

}
